-- AlterTable AziendaSettings: costi standard
ALTER TABLE "AziendaSettings" ADD COLUMN IF NOT EXISTS "costoGiornata" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "AziendaSettings" ADD COLUMN IF NOT EXISTS "indennitaTrasferta" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "AziendaSettings" ADD COLUMN IF NOT EXISTS "costoMutua" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "AziendaSettings" ADD COLUMN IF NOT EXISTS "costoPermesso" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "AziendaSettings" ADD COLUMN IF NOT EXISTS "costoFerie" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "AziendaSettings" ADD COLUMN IF NOT EXISTS "costoFestivo" DECIMAL(12,2) NOT NULL DEFAULT 0;
